version: '3.8'

services:
  pgdb:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ecommerse
    ports:
      - '5432:5432'
    # volumes:
    #   - db-data:/var/lib/postgresql/data

  # postgres:
  #   image: postgres:13.1
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   ports:
  #     - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
